Repository cosu-girls/coding-test-study, pull requests merged in 2025-07, with the labels that each got.

#5 [BOJ] 2798. 블랙잭
  .gitignore
  공통/2798. 블랙잭/oni.java
Labels: 브루트포스

#8 [BOJ] 7568. 덩치
  min/7568. 덩치/min.java
Labels: 브루트포스

#15 [BOJ] 2231. 분해합
  min/7568. 덩치/min.java
  oni/2231. 분해합/분해합_1.java
  oni/2231. 분해합/분해합_2.java
  oni/2798. 블랙잭/oni.java
Labels: 브루트포스

#16 [BOJ] 2309. 일곱 난쟁이
  oni/2309. 일곱 난쟁이/일곱 난쟁이.java
Labels: 브루트포스

#18 [BOJ] 22479. 알고리즘 수업 - 깊이 우선 탐색 1
  oni/24479. 알고리즘 수업 - 깊이 우선 탐색 1/알고리즘 수업 - 깊이 우선 탐색 1.java
Labels: 깊이 우선 탐색

#20 [BOJ] 24480. 알고리즘 수업 - 깊이 우선 탐색 2
  oni/24480. 알고리즘 수업 - 깊이 우선 탐색 2/알고리즘 수업 - 깊이 우선 탐색 2.java
Labels: 깊이 우선 탐색

#23 [BOJ] 2164. 카드2
  min/2164. 카드2/min.java
Labels: 큐
